name: QGIS Plugin Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t qgis-plugin-test .

      - name: Run tests in container
        run: |
          docker run --rm -v "${{ github.workspace }}:/plugin" qgis-plugin-test xvfb-run -a pytest tests
